TESTS_ENVIRONMENT += \
 TIMEOUT="$(TIMEOUT)" \
 MKTEMP="$(MKTEMP)"

check_PROGRAMS += \
 tests/sleep \
 tests/server \
 tests/client \
 tests/server-hang \
 tests/client-timeout

TESTS += \
 tests/sleep.sh \
 tests/basic.sh \
 tests/basic-ded-pool.sh \
 tests/timeout.sh

EXTRA_DIST += \
 tests/sleep.sh \
 tests/basic.sh \
 tests/basic-ded-pool.sh \
 tests/timeout.sh \
 tests/test-util.sh \
 tests/test-util-hang.sh \
 tests/test-util-ded-pool.sh
 
tests_server_SOURCES = \
 tests/server.c \
 tests/my-rpc.c

tests_server_hang_SOURCES = \
 tests/server-hang.c \
 tests/my-rpc.c

