TESTS_ENVIRONMENT += \
 TIMEOUT="$(TIMEOUT)" \
 MKTEMP="$(MKTEMP)"

# disable tests if there is no timeout command
if BUILD_TESTS
check_PROGRAMS += \
 tests/margo-test-init-ext \
 tests/margo-test-sleep \
 tests/margo-test-server \
 tests/margo-test-client \
 tests/margo-test-client-timeout

TESTS += \
 tests/sleep.sh \
 tests/basic.sh \
 tests/basic-ded-pool.sh \
 tests/basic-prio.sh \
 tests/basic-ded-pool-prio.sh \
 tests/timeout.sh

EXTRA_DIST += \
 tests/sleep.sh \
 tests/basic.sh \
 tests/basic-ded-pool.sh \
 tests/timeout.sh \
 tests/test-util.sh \
 tests/test-util-ded-pool.sh

tests_margo_test_server_SOURCES = \
 tests/margo-test-server.c \
 tests/my-rpc.c
endif
