noinst_PROGRAMS += examples/composition/composed-svc-daemon examples/composition/composed-benchmark

noinst_HEADERS += examples/composition/composed-client-lib.h\
		  examples/composition/data-xfer-proto.h\
		  examples/composition/data-xfer-service.h\
		  examples/composition/delegator-proto.h\
		  examples/composition/delegator-service.h

examples_composition_composed_svc_daemon_SOURCES = \
 examples/composition/composed-svc-daemon.c \
 examples/composition/data-xfer-service.c \
 examples/composition/delegator-service.c

examples_composition_composed_benchmark_SOURCES = \
 examples/composition/composed-benchmark.c \
 examples/composition/composed-client-lib.c

