src_libmargo_la_SOURCES += \
 src/margo-core.c \
 src/margo-diag.c \
 src/margo-bulk-pool.c \
 src/margo-globals.c \
 src/margo-handle-cache.c \
 src/margo-init.c \
 src/margo-logging.c \
 src/margo-timer.h \
 src/margo-timer.c \
 src/margo-util.c \
 src/margo-prio-pool.c
